### ISSUE TITLE
Deflex examples in Windows: Szenarioerstellung

### ISSUE THREAD

**Issue by jnettels** [quarree100/sandbox#1]
Hi there,

a while ago David provided me with the example "Deflex_Szenarioerstellung.py" to test deflex on my machine. A couple Windows-related issues prevented me from running it but I was able to fix them (there is a PR in reegis for those).

But I am still not able to run this script successfully.

If I run the first part:
```
years = [2012, 2013, 2014]
rmaps = ['de02','de17','de21','de22']

for year in years:
    for rmap in rmaps:
        basic_scenario.create_basic_scenario(year, rmap)
```
ultimately I crash with
```
Traceback (most recent call last):
  File "Deflex_Szenarioerstellung.py", line 15, in <module>
    basic_scenario.create_basic_scenario(year, rmap)
  File "C:\Users\Nettelstroth\anaconda3\envs\deflex\lib\site-packages\deflex\basic_scenario.py", line 700, in create_basic_scenario
    table_collection = create_scenario(regions, year, name, round_values)
  File "C:\Users\Nettelstroth\anaconda3\envs\deflex\lib\site-packages\deflex\basic_scenario.py", line 57, in create_scenario
    table_collection, regions, year, name, weather_year=weather_year
  File "C:\Users\Nettelstroth\anaconda3\envs\deflex\lib\site-packages\deflex\basic_scenario.py", line 513, in scenario_chp
    heat_b = reegis_powerplants.calculate_chp_share_and_efficiency(cb)
  File "C:\Users\Nettelstroth\anaconda3\envs\deflex\lib\site-packages\reegis\powerplants.py", line 509, in calculate_chp_share_and_efficiency
    elec_chp = eb.loc[(region, "output", row_chp), "electricity"]
  File "C:\Users\Nettelstroth\anaconda3\envs\deflex\lib\site-packages\pandas\core\indexing.py", line 1418, in __getitem__
    return self._getitem_tuple(key)
  File "C:\Users\Nettelstroth\anaconda3\envs\deflex\lib\site-packages\pandas\core\indexing.py", line 805, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "C:\Users\Nettelstroth\anaconda3\envs\deflex\lib\site-packages\pandas\core\indexing.py", line 910, in _getitem_lowerdim
    return self._getitem_nested_tuple(tup)
  File "C:\Users\Nettelstroth\anaconda3\envs\deflex\lib\site-packages\pandas\core\indexing.py", line 993, in _getitem_nested_tuple
    obj = getattr(obj, self.name)._getitem_axis(key, axis=axis)
  File "C:\Users\Nettelstroth\anaconda3\envs\deflex\lib\site-packages\pandas\core\indexing.py", line 1850, in _getitem_axis
    return self._get_label(key, axis=axis)
  File "C:\Users\Nettelstroth\anaconda3\envs\deflex\lib\site-packages\pandas\core\indexing.py", line 160, in _get_label
    return self.obj._xs(label, axis=axis)
  File "C:\Users\Nettelstroth\anaconda3\envs\deflex\lib\site-packages\pandas\core\generic.py", line 3735, in xs
    loc, new_index = self.index.get_loc_level(key, drop_level=drop_level)
  File "C:\Users\Nettelstroth\anaconda3\envs\deflex\lib\site-packages\pandas\core\indexes\multi.py", line 2826, in get_loc_level
    raise KeyError(key) from e
KeyError: ('DE01', 'output', 'Heizkraftwerke der allgemeinen Versorgung (nur KWK)')
```
What happens?
calculate_chp_share_and_efficiency() in powerplants.py gets handed the DataFrame ``eb`` and tries to access parts of the index with .loc. Upon inspection, it turns out that ``eb`` does not contain any entries with ``output``. Instead, this is what it looks like:
```
                                                                 electricity          gas    hard coal      lignite          oil    bioenergy        total
DE01 input   Heizkraftwerke der allgemeinen Versorgung (nur ...            0       317004       193329      69425.8            0      68357.3       715762
             Heizwerke                                                     0      86614.5        30063      2294.17        5.908      38955.6       197000
             Insgesamt                                               29899.2       773066  1.56304e+06  1.68564e+06       254342       909640   1.1187e+07
             Kernkraftwerke                                                0            0            0            0            0            0  1.08501e+06
             Kokereien                                                     0            0       227420         5470      30409.6            0       263300
             Raffinerien                                                   0            0            0            0       202474      94388.4  4.76492e+06
             Sonstige Energieerzeuger                                      0      19283.7        11125            0        13948        4.715      64362.8
             Steinkohlen- und Braunkohlenbrikettfabriken                   0            0            0       133793            0            0       133793
             Wasserkraftwerke                                        29899.2            0            0            0            0      75355.2       105254
             Windkraft-, Fotovoltaik- und andere Anlagen                   0            0            0            0            0       618696       639661
     primary Primärenergieverbrauch                                  -145602  3.00931e+06  1.66563e+06  1.65336e+06       535327  1.44418e+06  1.40239e+07
     tender  Energieangebot nach Umwandlungsbilanz               1.84631e+06  2.31063e+06       320730       100801  3.00477e+06       401824  9.94286e+06
     usage   Endenergieverbrauch                                 1.84631e+06  2.21679e+06       281946      94542.5  2.52831e+06       520426  8.90709e+06
```

This is where I have no clue how to proceed?
Any thoughts, @uvchik @beierd ?

**Comment by jnettels** [comment]
Ich habe das Problem gefunden, die config-Dateien wurden ebenfalls nicht mit UFT-8 eingelesen. Ist hier gefixed:
https://github.com/reegis/reegis/pull/23/commits/f92f9328fcf8cc32cce79356a71fbaf53e0555ed

**Comment by jnettels** [comment]
After my last fix yesterday, where I had to replace a custom expression that only worked on linux with `os.path.dirname()` (https://github.com/reegis/reegis/pull/23/commits/8fddbc89073a926cfd56582759b16c3b8fdb0121) and leaving it running over night, I can now confirm that the script is finishing without errors on Windows. Yay!

Now the only thing missing for my PR is the failing Travis build. But I cannot imagine how that AssertionError could be related to my commits.
