### ISSUE TITLE
Holoviews: cannot create folders in Ubuntu 20.04

### ISSUE THREAD

**Issue by dunland** [quarree100/sandbox#4]
Don't know if you're still working on this, but when I run the holoviews_sankey.py in Ubuntu 20.04, the script is seemingly not able to create directories, or something.
``` python
2021-06-02 11:56:11,699 ERROR    [Errno 2] No such file or directory: ''
Traceback (most recent call last):
  File "holoviews_sankey.py", line 61, in main
    bkplot = create_and_save_sankey(df, filename, sheet_name)
  File "holoviews_sankey.py", line 141, in create_and_save_sankey
    os.makedirs(os.path.dirname(filename))
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: ''
```

It worked out, though, when I disabled lines 139,140:
``` python
        # if not os.path.exists(os.path.dirname(filename)):
        #     os.makedirs(os.path.dirname(filename))
```

**Comment by jnettels** [comment]
You found a bug that I missed, thanks. (It tried to create an empty path.) Should be working as intended with commit 1e8d9a4.
